name: findit_mapper
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
webview_flutter: any
environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gsheets: ^0.4.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  google_sign_in_web: ^0.12.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/images/google.png
    - lib/images/logo.png
