// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALjoksZGbkdiAw0XYnsD5_WlkwVV247Hs',
    appId: '1:934645182621:web:a893a54c506911b0836474',
    messagingSenderId: '934645182621',
    projectId: 'primordial-gate-383309',
    authDomain: 'primordial-gate-383309.firebaseapp.com',
    storageBucket: 'primordial-gate-383309.appspot.com',
    measurementId: 'G-TB1EVZL13R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMfAe72vvv9_GJnw_W1HOcfBMpxEJwydA',
    appId: '1:934645182621:android:0eea6467e4980be9836474',
    messagingSenderId: '934645182621',
    projectId: 'primordial-gate-383309',
    storageBucket: 'primordial-gate-383309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDij9VCP9zoKKv8jLn0tEwXGw_RY-flMug',
    appId: '1:934645182621:ios:867c3e9724b0d708836474',
    messagingSenderId: '934645182621',
    projectId: 'primordial-gate-383309',
    storageBucket: 'primordial-gate-383309.appspot.com',
    iosClientId: '934645182621-a1bne4l0311a05n04hmnelns8vsknge2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finditMapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDij9VCP9zoKKv8jLn0tEwXGw_RY-flMug',
    appId: '1:934645182621:ios:867c3e9724b0d708836474',
    messagingSenderId: '934645182621',
    projectId: 'primordial-gate-383309',
    storageBucket: 'primordial-gate-383309.appspot.com',
    iosClientId: '934645182621-a1bne4l0311a05n04hmnelns8vsknge2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finditMapper',
  );
}
